language: php
php:
  - 5.6
  - 7.0
  - 7.1
before_script: composer install
script:
  - mkdir -p build
  - mkdir -p build/logs
  - vendor/bin/phpunit
after_success:
  - ls -l build/logs/
  - cat build/logs/clover.xml
  - travis_retry php vendor/bin/coveralls -v